# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: celery_task.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='celery_task.proto',
  package='celery_task',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63\x65lery_task.proto\x12\x0b\x63\x65lery_task\x1a\x1cgoogle/protobuf/struct.proto\"\x8b\x01\n\x0bTaskRequest\x12\x0c\n\x04task\x18\x01 \x01(\t\x12%\n\x04\x61rgs\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\'\n\x06kwargs\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x11\n\tcountdown\x18\x04 \x01(\x05\x12\x0b\n\x03\x65ta\x18\x05 \x01(\x05\"\x17\n\tTaskReply\x12\n\n\x02id\x18\x01 \x01(\t2Q\n\x11\x43\x65leryTaskService\x12<\n\x06\x43reate\x12\x18.celery_task.TaskRequest\x1a\x16.celery_task.TaskReply\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_TASKREQUEST = _descriptor.Descriptor(
  name='TaskRequest',
  full_name='celery_task.TaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task', full_name='celery_task.TaskRequest.task', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='celery_task.TaskRequest.args', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kwargs', full_name='celery_task.TaskRequest.kwargs', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='countdown', full_name='celery_task.TaskRequest.countdown', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eta', full_name='celery_task.TaskRequest.eta', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=204,
)


_TASKREPLY = _descriptor.Descriptor(
  name='TaskReply',
  full_name='celery_task.TaskReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='celery_task.TaskReply.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=229,
)

_TASKREQUEST.fields_by_name['args'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_TASKREQUEST.fields_by_name['kwargs'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['TaskRequest'] = _TASKREQUEST
DESCRIPTOR.message_types_by_name['TaskReply'] = _TASKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKREQUEST,
  '__module__' : 'celery_task_pb2'
  # @@protoc_insertion_point(class_scope:celery_task.TaskRequest)
  })
_sym_db.RegisterMessage(TaskRequest)

TaskReply = _reflection.GeneratedProtocolMessageType('TaskReply', (_message.Message,), {
  'DESCRIPTOR' : _TASKREPLY,
  '__module__' : 'celery_task_pb2'
  # @@protoc_insertion_point(class_scope:celery_task.TaskReply)
  })
_sym_db.RegisterMessage(TaskReply)



_CELERYTASKSERVICE = _descriptor.ServiceDescriptor(
  name='CeleryTaskService',
  full_name='celery_task.CeleryTaskService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=231,
  serialized_end=312,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='celery_task.CeleryTaskService.Create',
    index=0,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASKREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CELERYTASKSERVICE)

DESCRIPTOR.services_by_name['CeleryTaskService'] = _CELERYTASKSERVICE

# @@protoc_insertion_point(module_scope)
